### ISSUE TITLE
Blutopia still offline?

### ISSUE THREAD

**Issue by yefual** [HDVinnie/TrackerHub#29820]
**Describe the bug**
Blutopia is offline, I'm unsure what the status of the site is. Is it ever coming back online?

I saw there was a recent closed issue regarding Blutopia, but it is still is down for me. I'm unable to find any information about the outage anywhere on the internet.

Thank you for the time

**Comment by cooper7692** [comment]
been down for me as well, and still is.

**Comment by AlexFigas** [comment]
From vinnie: “ There is multiple failure points with ssd arrays, drives and more. It’s not good but a team is working on it. When time is right an announcement will be made. BLU has been removed from TrackerHub and Jackett in the meantime.”

**Comment by AlexFigas** [comment]
This post is misleading in a way. Simply saying I resigned leaves a void like I just dipped. That’s not the case. I am still here for BLU. I am still here for the torrent realm. I am still here developing UNIT3D. I will continue to help as I always have.

I’m not good at this and will admit that off the rip. So bear with me. I know I have a lot of haters so it is what it is but this is my attempt to let everyone know the story.

As most know I started UNIT3D from scratch in 2016 after being a dev for xbtit and u232 for many years under a different name and other trackers. I grew tired of hard to manage and simply bad code. In 2017 BLU was born as the first UNIT3D based tracker. I have dedicated the last 8 years to BLU and UNIT3D. They mean a ton to me and the community has grown tremendously. I helped as many other failing torrent communities that needed help with code and porting so they could survive.

BLU was self run for the first 4 years of its life in which we then started to accept donations. We never begged with weekly pms, news, etc. The community was strong and we chugged along fine.

We have gone through server issues in past and recovered just fine. These things happen and with daily backups it’s not an issue which we were doing. Locally and remote to other staff. One staff resigned. Then the other. This was in 2024.

BLU was booming. Peer growth, user growth, content growth and all around community growth was exceptional. Yes we recently had a horror month event. Saying we brought in thousands and thousands from it is just false though. I won’t debate it in a public manner. The community was booming and we brought back the upload bot server.

Here lies the issue. I have been drained. I had personal things I can’t and won’t get into. We recently had ssd failures which is a normal situation would be fine. Wait for host to replace and load a backup along with all kernel and dependency tuning. When the one staff resigned that was managing the off server backups I failed as a sysops to retract it to another staff and turn my local copies back on. That is on me. I take full responsibility and apologize. I am crushed just as much as you guys. Those that really know and interact with me would know this.

That being said this irc post makes it seem like I just went awol and resigned with nothing but echoes. That is not the case. Yes I have stepped down. Why? Because after 8 years I failed with something I know like the back of my hand. Simple backups. Is my personal draining and life issues an excuse. No. But it is what it is. It cannot be undone. For this I don’t deserve to be at BLU at that level anymore.

I am working with staff. I have transferred control. I am working to help and make things right from the outside. I will continue to develop UNIT3D that BLU and dozens and dozens of other trackers rely on. Anyone that was invited to BLU if they bring it back will be reinstated. I am already working on building list to resend invites for staff to use. Donor statues will be reapplied. Will it happen overnight. No. But BLUs community is one of the strongest so please don’t hate. Bear with us. For those that feel you were robbed. That’s simply not true and it’s really sad to hear that. Feel free to email me.

https://www.reddit.com/r/trackers/comments/1gplflw/blu_going_away/

**Comment by AlexFigas** [comment]
I think this issue can be closed. Wrong label and yes, still offline. Need to wait. They are working on it.

**Comment by yefual** [comment]
I appreciate the information!  Sorry I was unsure which label to select for the question, and I'm totally fine to close the issue if you'd like.

Sorry to sort of misuse the issue system here, I wasn't sure where else to ask.

Hopefully it isn't too difficult to bring back online!  Godspeed to anyone working on it
